version: 2
updates:
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "UTC"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "ShadowGlass0"
