version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "docker"
    rebase-strategy: auto
    schedule:
      interval: "daily"
    assignees:
      - "ShadowGlass0"
    pull-request-branch-name:
      separator: "-"
