version: 2
updates:
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Etc/UTC"
    pull-request-branch-name:
      separator: "-"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Etc/UTC"
    pull-request-branch-name:
      separator: "-"
