---
name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test docker build
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/docker-test

  build:
    name: Build & push image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version
        id: getver
        if: github.event_name != 'pull_request'
        run: |
          v_patch=$(grep "FROM ghcr.io/bplein/factorio-docker" Dockerfile | awk -F ':' '{print $2}' | xargs)
          {
            echo "v_patch=v$v_patch" 
            echo "v_minor=v$(echo "$v_patch" | awk -F '.' '{print $1"."$2}')"
            echo "v_major=v$(echo "$v_patch" | awk -F '.' '{print $1}')"
          } >> "$GITHUB_OUTPUT"
      - name: Add patch tag
        if: github.event_name != 'pull_request'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.getver.outputs.v_patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add minor tag
        if: github.event_name != 'pull_request'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.getver.outputs.v_minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add major tag
        if: github.event_name != 'pull_request'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.getver.outputs.v_major }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
